name = "Season 7 Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0558a33f34499731629e16ced05e0739522cae670a2443302c3ac247cec93ebf"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
