name = "Season 7 Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08de944a348f439889a08c595569fd1d922d52a8009bf3db8063dc1d963bc4cb"

[versions]
minecraft = "1.20.6"
quilt = "0.26.0-beta.1"

[options]
acceptable-game-versions = ["1.20.5"]
