name = "Season 7 Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27b0d3773627e0b6164d4fe89b22077baa0d413480d67116c6bc4704985df682"

[versions]
minecraft = "1.20.6"
quilt = "0.26.0-beta.1"

[options]
acceptable-game-versions = ["1.20.5"]
